# Generated by Django 4.1.4 on 2023-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_userprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
