# Generated by Django 4.1.4 on 2023-02-15 08:08

from django.db import migrations, models
import django.db.models.deletion
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0014_faq'),
        ('user_management', '0006_wishlist_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('order_id', models.CharField(blank=True, default=user_management.models.increment_order_id, editable=False, max_length=20, null=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Not Paid'), (2, 'Partial Paid'), (1, 'Paid')], default=0)),
                ('lock', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ('-created_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500, null=True)),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='user_management.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prints.product')),
            ],
        ),
    ]
