# Generated by Django 4.1.4 on 2023-04-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_orderitems_delivery_date_orderitems_shipping_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='shipping_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
