# Generated by Django 4.1.4 on 2022-12-31 17:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Media/slider')),
                ('project_done', models.IntegerField(default=0)),
                ('satisfied_clients', models.IntegerField(default=0)),
                ('awards_won', models.IntegerField(default=0)),
                ('expert_team', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
