# Generated by Django 4.1.4 on 2022-12-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_features_alter_aboutus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='image',
        ),
        migrations.AddField(
            model_name='features',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
