# Generated by Django 4.1.4 on 2022-12-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_remove_features_image_features_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='menu',
        ),
    ]
