# Generated by Django 4.1.4 on 2023-01-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0007_projecttype_project_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectType',
            new_name='Category',
        ),
    ]
