# Generated by Django 4.1.4 on 2023-01-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0009_category_available_quantity_category_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='lesson',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='additionalinformation',
            name='type',
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='prints.product'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
