# Generated by Django 4.1.4 on 2023-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0012_blog_slug_features_slug_industry_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.FileField(blank=True, default='Media/default.jpg', null=True, upload_to='Media/aboutus'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='Media/default.jpg', upload_to='Media/blog'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.FileField(blank=True, default='Media/default.jpg', null=True, upload_to='Media/industry'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='Media/default.jpg', upload_to='Media/product'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, default='Media/default.jpg', null=True, upload_to='Media/project'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, default='Media/default.jpg', null=True, upload_to='Media/service'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.FileField(blank=True, default='Media/default.jpg', null=True, upload_to='Media/technology'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(blank=True, default='Media/default.jpg', null=True, upload_to='Media/testimonial'),
        ),
    ]
