# Generated by Django 4.1.4 on 2023-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0015_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
