# Generated by Django 4.1.4 on 2023-04-15 02:36

from django.db import migrations, models
import prints.models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0016_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='Media/default.jpg', upload_to=prints.models.Photo.generate_path),
        ),
    ]
