# Generated by Django 4.1.4 on 2023-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0017_alter_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='technology_description',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='technology_title',
        ),
        migrations.AddField(
            model_name='settings',
            name='is_promotion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='promotion_background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='promotion_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
